source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.7.0"

# bound in the template on Cocoapods with next React Native release.
gem 'fastlane'
gem 'aws-partitions', '~> 1.894'
gem 'aws-sdk-core', '~> 3.191', '>= 3.191.3'
gem 'rexml', '~> 3.2', '>= 3.2.6'
gem 'nkf', '~> 0.2.0'
gem 'base64', '~> 0.2.0'
gem 'rake', '~> 13.1'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
