default_platform(:android)

platform :android do

  lane :beta do
    gradle(
        task: "clean"
    )
    
    gradle(
        task: "assemble",
        build_type: "Release"
    )
  
    release = firebase_app_distribution(
        app: "1:251933613737:android:f73cff374c4ce7a6ca13b8",
        service_credentials_file: "/Users/tintrung/training/training-react-native/training-react-native/SampleLogin/android/samplelogin-d5e65-650997352592.json",
        apk_path: "/Users/tintrung/training/training-react-native/training-react-native/SampleLogin/android/app/build/outputs/apk/release/app-release.apk",
        debug: true
    )
  end  
end