default_platform(:android)

platform :android do

  lane :beta do
    gradle(
        task: "clean"
    )
    
    gradle(
        task: "assemble",
        build_type: "Release"
    )
  
    release = firebase_app_distribution(
        app: "1:251933613737:android:f73cff374c4ce7a6ca13b8",
        firebase_cli_token: "0g7mbgeBQ3e-ECgYIARAAGBASNwF-L9Ir7Gl7NsYINbmDs4htAqyDr0tkTajGsIKKgMfeTXZoA7becAVsNdYrrqkd0u5zYbOZR3Y",
        apk_path: "/Users/tintrung/training/training-react-native/training-react-native/SampleLogin/android/app/build/outputs/apk/release/app-release.apk",
        debug: true
    )
  end  
end