default_platform(:android)

platform :android do

  lane :install_packages do
    yarn(
      command: 'install'
    )
  end

  lane :beta do
    release = firebase_app_distribution(
        app: "1:251933613737:android:f73cff374c4ce7a6ca13b8",
        service_credentials_file: "./samplelogin-d5e65-650997352592.json",
        apk_path: "./app/build/outputs/apk/release/app-release.apk",
        debug: true
    )
  end  
end