name: Android CI

on:
  push:
    workflow_dispatch:
      branches: [main]     # matches every branch
defaults:
 run:
  working-directory: SampleLogin/android

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

  build:
    name: Build
    needs: [ test ]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"


      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Yarn Install
        run: |
             yarn install             
      - name: Build application
        working-directory: SampleLogin/android
        run: |
             ./gradlew clean && ./gradlew assembleRelease   

      - run: echo "Build status report=${{ job.status }}."

  develop:
    name: Deploy on branch Develop
    needs: [ build ]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-33-jdk17

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        run: |
          extras fastlane
          fastlane android distribute_firebase
