name: "Build Android app"

on:
  workflow_dispatch:
    branches: [main]
    # can add push and pull_request here 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Yarn Install
        run: 
            shell: bash
            working-directory: ./SampleLogin
            yarn install             
      - name: Build application
        run: |
             cd ./SampleLogin/android
             ./gradlew clean && ./gradlew assembleRelease     
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

