name: Android Build & Deploy
 
on:
 workflow_dispatch:
    branches: [main]
defaults:
 run:
  working-directory: SampleLogin
   
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
 
   - name: Set up ruby env
     uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
     with:
      ruby-version: '3.1' # Not needed with a .ruby-version file
      bundler-cache: true
   - run: gem install bundler
   - run: bundle install
   - run: bundle init
   - name: Decode Service Account Key JSON File
     uses: timheuer/base64-to-file@v1
     id: service_account_json_file
     with:
       fileName: "google-services.json"
       encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}
 
   - name: Decode Keystore File
     uses: timheuer/base64-to-file@v1
     id: android_keystore
     with:
       fileName: "sample-login.keystore"
       encodedString: ${{ secrets.KEYSTORE_FILE }}
 
   - name: Build & deploy Android release
     working-directory: SampleLogin/android
     run: bundle exec fastlane android deploy
     env:
       KEYSTORE_FILE: ${{ steps.sample-login.outputs.filePath }}
       KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
       KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
       KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
       ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}
 
   - name: Upload build artifacts
     uses: actions/upload-artifact@v2
     with:
       name: assets
       path: |
         ${{ github.workspace }}/app/build/outputs/bundle/release