name: "Build Android app"

env:
  # The name of the main module repository
  main_project_module: SampleLogin

  # The name of the Play Store
  playstore_name: SampleLogin App


on:
  workflow_dispatch:
    branches: [main]
    # can add push and pull_request here 
defaults:
 run:
  working-directory: SampleLogin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Yarn Install
        run: |
             yarn install             
      - name: Build application
        working-directory: SampleLogin/android
        run: |
             ./gradlew clean && ./gradlew assembleRelease     
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: SampleLogin/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3

       # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/android/app/build/outputs/apk/release/app-release.apk


